### ISSUE TITLE
'yarn install' doesn't do anything

### ISSUE THREAD

**Issue by Brubhubedits** [Geczy/ipa-bot#12]
`Danie@DESKTOP-2Q8TO12' MINGW64 ~/ipa-bot (main)`
`$ yarn install`
`bash: yarn: command not found`

**Comment by Geczy** [comment]
install yarn?

**Comment by Brubhubedits** [comment]
How am I actually meant to install it if the command isn't recognised? Is there a link to a repo?

**Comment by Geczy** [comment]
google how to install yarn lol
