### ISSUE TITLE
syntax error near unexpected token `}'

### ISSUE THREAD

**Issue by arm64x** [Geczy/ipa-bot#3]
Hi, I get an error when I run the following command

bash ./src/bash-decryptor/download-ipa.sh 1137397744 us 0123456789 ''

error

./src/bash-decryptor/download-ipa.sh: line 278: syntax error near unexpected token `}'
./src/bash-decryptor/download-ipa.sh: line 278: `}'

**Comment by Geczy** [comment]
@spinfal was there a syntax error in what you merged? i never pulled it down 😂

**Comment by spinfal** [comment]
that's weird, i never ran into any syntax errors even when running manually

**Comment by spinfal** [comment]
@arm64x can you try replacing `download-ipa.sh` with this updated file please: https://cdn.spin.rip/r/download-ipa.sh
let me know if it works at all, if not i'll take a closer look to see if there are any smaller issues.

**Comment by arm64x** [comment]
Hi, thanks for the help but now another error appears.

bash ./src/bash-decryptor/download-ipa.sh 1137397744 us 0123456789 ''

./src/bash-decryptor/download-ipa.sh: line 124: 🔍 Looking up app in the ${countryCode^^} region...: bad substitution

Fix: 

change line 124
echo "🔍 Looking up app in the ${countryCode^^} region..."
to
echo "🔍 Looking up app in the $(echo "$countryCode" | tr '[:lower:]' '[:upper:]') region..."
