### ISSUE TITLE
Can this only be deployed on a local server?

### ISSUE THREAD

**Issue by Cregin** [Geczy/ipa-bot#7]
Can I deploy it on vps?

**Comment by Geczy** [comment]
if you can virtualize access to the iphone, you can deploy to vps. needs usb + ssh access

**Comment by Cregin** [comment]
> if you can virtualize access to the iphone

How to virtualize access to iPhone?I mean Node.js and Yarn deployed in vps, iPhone at home without connecting computers

**Comment by Geczy** [comment]
idk, you'd have to google that one. something about usb virtualization. try searching connect usb to a vps
